name: Test Scripts

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test_scripts:
    runs-on: 'ubuntu-latest'
    if: "! contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Test scripts
      run: ./test/run.sh
